global using System;
global using System.Collections.Concurrent;
global using System.Collections.Generic;
global using System.IO;
global using System.Numerics;
global using System.Text;
global using System.Text.Json;
global using System.Threading;
global using Dalamud.Bindings.ImGui;
global using Dalamud.Game.ClientState.JobGauge.Types;
global using Dalamud.Game.ClientState.Objects.Enums;
global using Dalamud.Game.ClientState.Objects.Types;
global using ECommons.DalamudServices;
global using LosPr.BLM.Data;
global using LosPr.BLM.Core;
global using LosPr.BLM.Diagnostics;
global using PromeRotation.Data;
global using PromeRotation.Extensions;
global using PromeRotation.Helpers;
global using PromeRotation.LogSystem;
global using PromeRotation.Managers;
global using PromeRotation.Rotation;
global using PRCore = PromeRotation.Core.Core;
global using PRGameData = PromeRotation.Core.GameData;
