<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>Los</AssemblyName>
    <RootNamespace>LosPr</RootNamespace>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Deterministic>true</Deterministic>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <EmbeddedResource Include="BLM\UI\Assets\BlackCatFamiliar.png"
                      LogicalName="LosPr.BLM.UI.Assets.BlackCatFamiliar.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="PromeRotation.SDK.API15"
                      Version="0.1.0-preview.6"
                      PrivateAssets="all" />
  </ItemGroup>
</Project>
